server:
  port: 8081
spring:
  application:
    name: fraud
  datasource:
    password: fraud
    url: jdbc:postgresql://localhost:5433/fraud
    username: fraud
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true